### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by ginsterbusch** [DavidLibeau/mastodon-tools#5]
Was bored and needed a warm-up before throwing myself on an ongoing, "the neverending Story"-like project of a client .. so I did an almost complete rewrite of your mastodon-embed plugin ;)

See https://github.com/ginsterbusch/mastodon-embed

**Comment by DavidLibeau** [comment]
:man_dancing: Seems really cool !

I have a few questions : 
Can you add more docs of what is possible to embed with which options ?
And how do you want to manage that now ? Publishing the plugin on WordPress.org ? etc

Thanks !

**Comment by ginsterbusch** [comment]
The readme file shows most of it aka its pretty much self-explaining. The only part which is not yet covered is the filter hooks, but a quick look in the source code should fix that (PHPDoc). Code examples and screenshots I'm going to add later on, too ;)

cu, w0lf.

**Comment by ginsterbusch** [comment]
About publishing it to the WP plugin repo: Well .. these days its a pretty tedious process (being a member of the Team Review Team myself; although not active anymore, I still get all the news and stuff), but I gonna give it a try, as soon as I got all the bells and whistles added properly ;)

cu, w0lf.
