### ISSUE TITLE
Appeared blank

### ISSUE THREAD

**Issue by itsumonotakumi** [DavidLibeau/mastodon-tools#7]
Hi, I wrote about this "Mastodon Embed" for Japanese at my blog.
https://takulog.info/mastodon-embed-wordpress-plugin/

OK => [mastodon url="https://pawoo.net/@itsumonotakumi/2155516″][/mastodon]

But some embed toot was not displayed on my blog.

NG => [mastodon url="https://3.nu/@sippowhite/247156″][/mastodon]
NG => [mastodon url="https://mstdn.jp/@omimi/3768536″][/mastodon]
NG => [mastodon url="https://mstdn.jp/@nippon/3783357″][/mastodon]

I try to use some case, and I think there are some mastodon instances that WP use this plugin.
Maybe I think this plugin couldn't use some host names, "mstdn.jp", "3.nu" and any more...
Do you know this cause of this issue?

**Comment by DavidLibeau** [comment]
Yes, it's a known issue. Thanks for reporting.
It is due to server config of the instances, that disallow iframe, I think.

Normally it is fixed with this version (that I am considering to merge) : https://github.com/ginsterbusch/mastodon-embed

**Comment by itsumonotakumi** [comment]
Thank you for your quick reply!I understood it. Please close this case.

Maybe Japanese users use version 1.3 because we almost see below: 
https://ja.wordpress.org/plugins/embed-mastodon/
