### ISSUE TITLE
Autopost to Wordpress Mastodon Plugin

### ISSUE THREAD

**Issue by simonfrey** [DavidLibeau/mastodon-tools#8]
Hey,

would be awesome to get listet at your webpage!
I developed a Wordpress Plugin that automatically post all your posts to mastodon.

Wordpress Plugin Directory: https://wordpress.org/plugins/autopost-to-mastodon/
Sourcecode: https://github.com/L1am0/mastodon_wordpress_autopost
My Website: http://l1am0.eu

**Comment by DavidLibeau** [comment]
Hi, Do you want like a DNS `something.mastodon.tools` ?

**Comment by simonfrey** [comment]
Yes 👍 
_autopost.mastodon.tools_ would be nice :D

**Comment by DavidLibeau** [comment]
Ok, which redirect to a server (which IP ?) or an url (which one ?)

**Comment by simonfrey** [comment]
Oh sorry i ment to be listed on the page. As with your own WP plugin:
http://mastodon.tools/wordpress/

To have some information about it on there..i have no own website for the plugin. So a subdomain forward would not work out.

**Comment by DavidLibeau** [comment]
As this repo is only what I coded, I don't really know how to handle that. How to add that…

**Comment by simonfrey** [comment]
I opened a pull request wich is adding the plugin to the repo and the site.

Thanks

**Comment by simonfrey** [comment]
Do you have any questions regarding the pull request?
https://github.com/DavidLibeau/mastodon-tools/pull/9
